# .github/workflows/stale.yml
# Manages stale issues and PRs

name: Stale Issue Management

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          # Issue settings
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions!
          stale-issue-label: 'stale'
          days-before-issue-stale: 60
          days-before-issue-close: 14
          exempt-issue-labels: 'pinned,security,bug,enhancement'

          # PR settings
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not had
            recent activity. It will be closed in 7 days if no further activity occurs.
            Please update or comment if this PR should remain open.
          stale-pr-label: 'stale'
          days-before-pr-stale: 30
          days-before-pr-close: 7
          exempt-pr-labels: 'pinned,work-in-progress'

          # General settings
          operations-per-run: 30